version: '3.8'

services:
  ghost-multisite:
    build:
      context: .
      dockerfile: Dockerfile.multisite
    container_name: ghost-multisite
    ports:
      # Ghost CMS
      - "2368:2368"
      # LibSQL database servers (one per site)
      - "8081:8081"  # demo1 database
      - "8082:8082"  # demo2 database  
      - "8083:8083"  # demo3 database
    volumes:
      # Persist database files and content
      - ghost_content:/var/lib/ghost/content
      # Development: mount local code changes (optional)
      # - ./ghost:/var/lib/ghost/ghost
    environment:
      NODE_ENV: production
      GHOST_INSTALL: /var/lib/ghost
      GHOST_CONTENT: /var/lib/ghost/content
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2368/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: ghost-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: Nginx proxy for multi-site routing
  nginx:
    image: nginx:alpine
    container_name: ghost-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/sites:/etc/nginx/sites-enabled:ro
    depends_on:
      - ghost-multisite
    restart: unless-stopped

volumes:
  ghost_content:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: ghost-multisite-network